### ISSUE TITLE
Link to shutdown Tails doc is broken

### ISSUE THREAD

**Issue by epiccurious** [BenWestgate/Bails#39]
On the 'Setup almost complete' popup window, the `shutdown Tails` link is broken. Clicking on it doesn't appear to do anything, while the second link to `read the documentation` works fine.

The fix is to replace:
`file:///usr/share/doc/tails/website/doc/first steps/shutdown/index.en.html`

with:
`file:///usr/share/doc/tails/website/doc/first steps/shutdown.en.html`

![image](https://github.com/BenWestgate/Bails/assets/109078515/96cc77a1-0630-46e7-9e5b-3d41358ecc1f)

**Comment by epiccurious** [comment]
@BenWestgate do you want me to create a PR?

**Comment by BenWestgate** [comment]
both URIs you linked are wrong

file:///usr/share/doc/tails/website/doc/**first_steps**/shutdown.en.html

I pushed an update fixing the uri
