### ISSUE TITLE
spooky integration: suggest AppImage isolation

### ISSUE THREAD

**Issue by llamabyte** [BenWestgate/Bails#64]
Hi, great great idea !

I really like this but i don't like how it integrates with tails. 

Would it be possible to have it as an appimage, that way i can isolate it and still have it download the dependencies it needs (bitcoind) and run whaterver daemons it needs.

It's kind of spooky to give all these persmission and have itpop up as an integrated app alongside other native apps, including my unlocked drive. I am aware i could intall it on a fresh tails and avoid that risk, but

**Comment by BenWestgate** [comment]
Thank you for your feedback and interest in Bails! We appreciate your support and are glad to hear that you like the idea.

Regarding your concerns about the integration with Tails, we understand your desire for increased isolation and security. We are actively exploring ways to improve the user experience and address these concerns. 

I'd like to assure you Bails does not use elevated permissions, that was a major design change from the old project. While it limited options, I felt it was the right way to go to make the software require less trust to test and be more secure to use. And your idea may be a further step in that direction.

We updated the README.md instructions yesterday to advise users not to Create a Persistent Storage before running Bails. And today I am going to make it fail more gracefully if they have ignored this. Ultimately we believe users should have a dedicated Bails USB for Bitcoin stuff so having it install to an existing Persistent Storage was not a priority use case, but I will try to support it on a best effort basis.

Providing Bails as an AppImage, would allow you to run it in an isolated environment and manage its dependencies. This would provide you with more control over the application's access and interactions with other parts of your system. It's only dependency besides Tails itself is Bitcoin core.

As for the application menu shortcuts and autostart, they serve important functional purposes. Bails aims to provide an easy integrated experience for new users. The application menu allows for convenient access to Bails' features, including creating and restoring codex32 seed backups, creating backup USBs, updating bitcoin core and cloning Bails for a friend.

I have another repository named `bitcoin-core-on-tails` that we could put a stripped down version of the bitcoin core installation script into.

Such that it doesn't do anything else and can be be distributed as a single file. Then that file can become a dependency for this project Bails, which includes the codex32-enabled wallet and guide for setting up a Persistent Storage and help for remembering the passphrase.

It seems more experienced users are having more issues with the design or scope of Bails than beginners are who are finding it quite easy to use.

We take security and privacy very seriously, and we're committed to making Bails a trustworthy and reliable tool for Bitcoin users. Your feedback is invaluable in helping us improve Bails and make it even better.

We will carefully consider your suggestion and can work towards offering Bails as an AppImage in the future. In the meantime, if you have any other suggestions or questions, please feel free to share them with us.

Thank you for testing Bails, and let me know which of these solutions would best meet your needs and expectations.

**Comment by BenWestgate** [comment]
Towards closing this issue, the bails-wallet code is being refactored into a Python package, as is the codex32 backend.

After this bails should really be 1-2 executables that just do a normal application installation.

I may be able to ship bails as a flatpack package. I'm more on the system administration side than software developer so packaging software is newer to me but I'm learning.

**Comment by BenWestgate** [comment]
@epiccurious: Should this issue be closed?

**Comment by epiccurious** [comment]
> I am aware i could intall it on a fresh tails and avoid that risk, but

That the workaround is using a fresh install of Tails.

@llamabyte can you provide more context for why you want to run this in an existing Tails setup?

**Comment by BenWestgate** [comment]
Here's what can be identified:

He doesn't want shortcuts, autostart, he only wants bitcoin to download and write what it needs to function.

He also seems to have set an administration password to mount his internal storage.

The current master would be more convenient for him as the choose datadir dialog from Bitcoin is shown where he could have selected his internal storage. Although that would unfortunately write the wallet folders to the internal storage too. That will get fixed with #81.

This can be moved to the Bitcoin Core on Tails repository if I commit to making that project do nothing other than install bitcoin core to Tails. That will close this issue.

**Comment by BenWestgate** [comment]
@llamabyte: a work around is to install bails then disable dotfiles afterwards. This will remove the shortcuts and autostarts.

You can find the executable to run bitcoin-qt in `/live/persistence/TailsData_unlocked/dotfiles/.local/bin` you will have to specify the datadir every start up use: `~/Persistent/.bitcoin`.

**Comment by BenWestgate** [comment]
OP has abandoned this issue and I have no plans to separate "install-core" into a separate repository at this time as not one person has requested this functionality.

That would be nice to allow for competition in the backup system and can be reopened in the future should anyone want to do that.

**Comment by BenWestgate** [comment]
OP has abandoned this issue and I have no plans to separate "install-core" into a separate repository at this time as not one person has requested this functionality.

That would be nice to allow for competition in the backup system and can be reopened in the future should anyone want to do that.

**Comment by BenWestgate** [comment]
https://gitlab.tails.boum.org/tails/tails/-/issues/16564

We will investigate shipping Bails as a cross platform Flatpak in the future. This won't be as easy to install as the current method however until Tails support Flatpaks by default.
