### ISSUE TITLE
New Feature: Panic Mode

### ISSUE THREAD

**Issue by BenWestgate** [BenWestgate/Bails#81]
Inspired by: [OWASP User Privacy Protection Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/User_Privacy_Protection_Cheat_Sheet.html#panic-modes)

If wallets are placed into encrypted volumes, panic mode can load fake decoy watch-only wallets if the user entered their distressed password. The key origin information can be spoofed. These could be sub-accounts of the real master-seed for recovery purposes.

Loading a private_keys_enabled wallet is more difficult as in order to look like the real wallet, the master xprv needs to be in the descriptors, which means grinding for master xprvs to match the real one's fingerprint.

"Adversaries must have no way to know a panic mode already exists..." this means while the feature would be opt-in, every user whether they set-up panic mode or not, would have to have enough encrypted volumes created for plausible deniability of those who do use it.

I can possibly use [Veracrypt Hidden Volumes](https://www.veracrypt.fr/en/Hidden%20Volume.html) for this. It must be able to be created and decrypted without an administration password setup.

"The password for the hidden volume must be substantially different from the password for the outer volume."

This applies regardless of if I use LUKS2 volumes or Veracrypt. A good default would be for people who do NOT use panic mode to have to enter their Persistent Storage Passphrase to Load their wallets. Then users who want a Panic Mode can create a "substantially different" passphrase for their Real wallet and an attacker will see the Fake wallet with the default passphrase.

**Comment by epiccurious** [comment]
ACK

> These could be sub-accounts of the real master-seed for recovery purposes.

How would this work? Would distress sub-accounts be visible to the user in the standard wallet or only relevant for a recovery/sweep of funds? By sub-accounts, are you referring to a custom HD derivation path.

> grinding for master xprvs to match the real one's fingerprint

How much of a time expensive would grinding be?

> every user whether they set-up panic mode or not, would have to have enough encrypted volumes created for plausible deniability

Good design choice.

**Comment by BenWestgate** [comment]
The reason the fingerprint should match the real wallet is the new #72 uses the bip32 fingerprint in bech32 as a default identifier for codex32 strings. If the extortioner had access to a share and your Persistent Storage, he would know your wallet is probably a fake if the identifier didn't match the share. Although you can set custom identifiers and you can manually fake your own key origin info, or say the codex32 shares are not yours, these are not the most plausible denials for the mismatch.

**Comment by BenWestgate** [comment]
For decoy wallets, when the user has the default share identifier, we will brute force the next BIP85 derived extended private master key that has the same identifier, that way decoys can spend without giving away that they are decoy wallets.

On restore, the master xprv can be brute forced again so nothing needs to be backed up.

**Comment by BenWestgate** [comment]
Note: clear text wallets will be removed from the Beta in order to cheaply get clone for a friend functionality. The best way to clone is just always encrypt all your sensitive wallet data then the root of the Persistent Storage is safe to share.

Before a wallet is created or restored, the user will be asked to create a new vault if the wallet name doesn't specify a vault that is already open. This allows one to have multiple wallets in a specific vault for convenience. Possibly not specifying a vault name just the wallet name, makes the root of the encrypted file system labeled as wallet name its wallet folder.

**Comment by BenWestgate** [comment]
The code in install-core has been commented where this will affect it. The current design will be to create a symlink to /media/$USER named wallets in the datadir. Alternatively, walletdir=/media/$USER could be set in Bitcoin.conf.

There will be no option to not have encrypted wallets. That way we get the clone feature easily right after this is in.

**Comment by BenWestgate** [comment]
Users need to choose a passphrase to encrypt their vaults.

The overall strength of the encryption depends strongly on this passphrase, so they should take care to choose a passphrase that is not easy to guess. It should not be a word or sentence found in dictionaries, or a phrase that could be easily associated with you.

A good passphrase will contain a mixture of letters, numbers and punctuation. Passphrases are recommended to have a length of 20 or more characters.

We should also show a zxcvbn entropy estimate of the passphrase. Including the difference between other passphrases already in use.

Giving a diceware suggestion would also likely be helpful.
